CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
ALTER DISTRIBUTION ds1 ATTACH RELATION pgbench_branches DISTRIBUTION KEY bid;
ALTER DISTRIBUTION ds1 ATTACH RELATION test1 DISTRIBUTION KEY id SCHEMA sh1;
CREATE KEY RANGE FROM 0 ROUTE TO sh1 FOR DISTRIBUTION ds1;
