create distribution ds1 column types integer;
ADD KEY RANGE krid2 FROM 10000000 ROUTE TO sh2 FOR DISTRIBUTION ds2;
ADD KEY RANGE krid1 FROM 0 ROUTE TO sh1 FOR DISTRIBUTION ds1; 
ALTER DISTRIBUTION ds1 ATTACH RELATION articles DISTRIBUTION KEY id;  


